# Generated by Django 3.2.7 on 2022-02-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211221_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'СДАННЫЕ ОБЪЕКТЫ',
                'verbose_name_plural': 'СДАННЫЕ ОБЪЕКТЫ',
                'ordering': ('-id',),
            },
        ),
    ]
