# Generated by Django 3.2.9 on 2022-01-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например Заголовок: Кирпич мне в голову', max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(help_text='Уютные Квартиры', upload_to='service', verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
