# Generated by Django 3.2.7 on 2022-02-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220203_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='backround_image',
            field=models.ImageField(default=1, upload_to='backround_image/'),
            preserve_default=False,
        ),
    ]
