# Generated by Django 3.2.7 on 2022-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting_backround_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='working_hours',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
