# Generated by Django 3.2.9 on 2022-01-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Досматов Дилмурат', max_length=255, verbose_name='Название')),
                ('position', models.CharField(help_text='Например: construction-engineer', max_length=255, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='биография')),
                ('image', models.ImageField(upload_to='team', verbose_name='')),
            ],
        ),
    ]
